env:
  - ARCH=amd64
  - ARCH=s390x

before_script: echo "before"$ARCH
script: echo $ARCH
after_script: echo "after"$ARCH

jobs:
  include:
    - stage: deploy manifest
      env: ARCH=s390x
      script: echo Deploy
      
