sudo: required
 
services:
 - docker

env:
  matrix:
    - ARCH=s390x
    - ARCH=amd64
before_install:
    # prepare qemu
    - docker run --rm --privileged multiarch/qemu-user-static:register --reset
    - echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json
    - sudo service docker restart
    - sudo update-binfmts --enable qemu-"${ARCH}"
    - docker build --compress -t dmkif/gotty-"${ARCH}" -f Dockerfile."${ARCH}" .

script:
   - docker images dmkif/gotty-"${ARCH}"
