sudo: required
 
services:
 - docker
addons:
  apt:
    packages:
    - qemu 
    - qemu-user-static 
    - qemu-user 
    - binfmt-support
    
env:
 - os: linux
      dist: trusty
      sudo: required
  matrix:
    - ARCH=s390x
    - ARCH=amd64
before_install:
    - echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json
    - sudo service docker restart
    - docker run --rm --privileged multiarch/qemu-user-static:register --reset
    - touch qemu-"${ARCH}"-static
    - cp /usr/bin/qemu-*-static .
    - sed s/'@@ARCH@@'/${ARCH}/g Dockerfile > Dockerfile."${ARCH}"
    - docker version
    - sudo docker build --compress --squash -t dmkif/gotty-"${ARCH}" -f Dockerfile."${ARCH}" .

script:
   - docker images dmkif/gotty-"${ARCH}"
