sudo: required
services:
- docker
language: bash

env: 
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - REPO=dmkif/gotty   
  matrix:
  - ARCH=s390x
  - ARCH=amd64
 
before_install:
  - sudo apt update && sudo apt -y install qemu binfmt-support qemu-user-static
  - touch qemu-user-static/qemu-"${ARCH}"-static
  - echo "{\"experimental\":true}" | sudo tee /etc/docker/daemon.json
  - sudo service docker restart
  - sed s/"@@ARCH@@"/"${ARCH}"/g Dockerfile > Dockerfile."${ARCH}"
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset

script:
  - export TAG=`if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master" ]]; then echo "latest"; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi`
  - travis_wait 60 docker build --compress --squash -t "${REPO}-${ARCH}:${TAG}" -f Dockerfile."${ARCH}" .
  - docker images dmkif/gotty-"${ARCH}"
