sudo: required
dist: trusty

services:
- docker

env: 
  - ARCH=s390x
  - ARCH=amd64
 
install:
  - sudo apt update && sudo apt -y install qemu binfmt-support qemu-user-static
  - sudo cp /usr/bin/docker /usr/bin/docker-cli.bak
  - sudo curl -fsSL https://github.com/clnperez/cli/releases/download/1.0/docker-linux-amd64 -o /usr/bin/docker
  - echo "{\"experimental\":true}" | sudo tee /etc/docker/daemon.json
  - sudo service docker restart
  - sed s/"@@ARCH@@"/"${ARCH}"/g Dockerfile > Dockerfile."${ARCH}"
  - git clone https://github.com/computermouth/qemu-static-conf.git
  - sudo mkdir -p /lib/binfmt.d
  - sudo cp qemu-static-conf/*.conf /lib/binfmt.d/
  - sudo systemctl restart systemd-binfmt.service

before_script:
  - export TAG=`if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master" ]]; then echo "latest"; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi`

script:
  - travis_wait 60 docker build --compress --squash -t "${REPO}-${ARCH}:${TAG}" -f Dockerfile."${ARCH}" .
  - docker images "${REPO}-${ARCH}:${TAG}"

after_script:
  - docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORT"
  - if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master" ]]; then
    docker tag "${REPO}"-"${ARCH}":"${TAG}" "${REPO}"-"${ARCH}":"${TRAVIS_BUILD_NUMBER}";
    docker push "${REPO}"-"${ARCH}":"${TRAVIS_BUILD_NUMBER}";
    fi 
  - docker push ${REPO}-${ARCH}:${TAG}
  - docker logout

jobs:
 include:
  -stage: Deploy Manifest
  if: branch = master
  script: 
   - echo "{\"experimental\":true}" | sudo tee /etc/docker/daemon.json
   - sudo service docker restart
   - docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORT"
   - docker pull "${REPO}-s390x";
   - docker pull "${REPO}-amd64";
   - docker manifest create "${REPO}" "${REPO}-s390x" "${REPO}-amd64";
   - docker manifest annotate --arch=$ARCH --os=linux 
   - docker manifest push "${REPO}";
   - docker manifest inspect $REPO
   - docker logout