sudo: required 
services:
 - docker
 
env:
  matrix:
    - ARCH=s390x
    - ARCH=amd64
before_install:
    - sudo apt update && sudo apt -y full-upgrade && sudo apt -y install qemu build-essential binfmt-support 
    - git clone git://git.qemu.org/qemu.git
    - cd qemu
    - git submodule update --init --recursive
    - ./configure --prefix=$(cd ..; pwd)/qemu-user-static --static --disable-system --enable-linux-user
    - make -j8 && make install
    - cd ..
    - touch qemu-user-static/qemu-"${ARCH}"
    - echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json
    - sudo service docker restart
    - docker run --rm --privileged multiarch/qemu-user-static:register --reset
    - sed s/'@@ARCH@@'/${ARCH}/g Dockerfile > Dockerfile."${ARCH}"
    - docker version
    - sudo docker build --compress --squash -t dmkif/gotty-"${ARCH}" -f Dockerfile."${ARCH}" .

script:
   - docker images dmkif/gotty-"${ARCH}"
