sudo: required

addons:
  apt:
    packages:
    - qemu 
    - qemu-user-static 
    - qemu-user
    - qemu-system-s390x   
    - binfmt-support

services:
 - docker

env:
  matrix:
    - ARCH=s390x
    - ARCH=amd64
before_install:
    - echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json
    - sudo service docker restart
    - sudo update-binfmts --enable qemu-"${ARCH}"
    - docker build --compress -t dmkif/gotty-"${ARCH}" -f Dockerfile."${ARCH}" .

script:
   - docker images dmkif/gotty-"${ARCH}"
